version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    # set limit to 1 as auto-merge seems to fail if more than 1
    open-pull-requests-limit: 1
    assignees:
      - "@navikt/tpts"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "@navikt/tpts"
