version: "3.8"

services:
  backend:
    image: tpts-mottak
    ports:
      - "8081:8080"

  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    command: >
      --openid.provider azure
      --bind-address 0.0.0.0:3000
      --ingress http://localhost:3000
      --upstream-host host.docker.internal:8081
    ports:
      - "8080:3000"
    environment:
      AZURE_APP_WELL_KNOWN_URL: ${AZURE_APP_WELL_KNOWN_URL}
      AZURE_APP_CLIENT_ID: ${AZURE_APP_CLIENT_ID}
      AZURE_APP_JWK: ${AZURE_APP_JWK}
