apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-mottak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tiltakspenger-mottak.dev.intern.nav.no
  azure:
    application:
      enabled: true
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  envFrom:
    - configmap: tiltakspenger-mottak-dev
  gcp:
    sqlInstances:
      - name: tpts-tiltakspenger-mottak-dev
        type: POSTGRES_14
        diskAutoresize: false # prod: true
        pointInTimeRecovery: false # prod: true
        databases:
          - name: mottak
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tpts-tiltakspenger-flate
          namespace: tpts
          cluster: dev-gcp
