apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-mottak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  envFrom:
    - configmap: {{ configmap }}
