apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-mottak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress.url }}
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  tokenx:
    enabled: true
  envFrom:
    - configmap: {{ configmap }}
  gcp:
    sqlInstances:
      - name: {{ sqlInstances.name }}
        type: POSTGRES_14
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        databases:
          - name: mottak
            envVarPrefix: DB
