name: Auto Merge dependabot
on: [ pull_request_target ]
permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  dependabot:
    name: Merge
    needs: build
    runs-on: ubuntu-latest
    # Only allow dependabot from this repo and not via forks
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
