name: detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '28 3 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detekt:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.19.0
        with:
          args: --fail-fast --config config/detekt.yml
