name: detekt

on: push

jobs:
  detekt:
    name: "Scan with Detekt"
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.19.0
        with:
          args: --build-upon-default-config --config config/detektiv.yml
